name: bgfinancas
version: '3.7.1'
summary: Personal Finances Manager
description: |
  BG Finanças is a open source software to control your financial life,
  your focus is to use accounts to store money and launch 
  expenses / revenues to alter the balance account. Counting with your 
  planning module, reports and ability to track spending, BG Finanças 
  will be a great ally in the management of your money.

icon: icon.png
grade: stable
confinement: strict

apps:
  bgfinancas:
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64
      JAVA_TOOL_OPTIONS: "-Duser.home=$SNAP_USER_COMMON"
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
      XDG_DATA_HOME=$SNAP/usr/share
      FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
      FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf
      HOME=$SNAP_USER_DATA
    command: java -jar $SNAP/jar/bgfinancas.jar
    desktop: usr/share/applications/bgfinancas.desktop
    plugs: [network, home, desktop, desktop-legacy, wayland, unity7, x11]

parts:
  bgfinancas:
    plugin: ant
    source: .
    override-build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      ant main
      cp -R jar $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - openjdk-8-jdk
      - openjfx
    stage-packages:
      - openjdk-8-jre
      - openjfx
    after: [desktop-glib-only]
  launcher:
    plugin: dump
    source: .
    organize:
      'bgfinancas.desktop': usr/share/applications/bgfinancas.desktop
    after: [bgfinancas]
